version: '3.1'
services:
  mongo:
    restart: always
    image: mongo
    container_name: unifes_mongo
    volumes:
      - ./data/mongo:/data/db
  dev:
    build: .
    container_name: unifes_dev
    volumes:
      - .:/workspace/unifes
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      DEBUG: unifes
    tty: true
    command: 'node-dev ./bin/www'
